title: Charles-Alexandre Mattelaer
description: Computational (bio)chemist
url: "https://camattelaer.github.io"
baseurl: ""

author:
  name: Charles-Alexandre Mattelaer
  avatar: /assets/images/bio.jpg
  bio: "Pharmacist by study, Computational Chemist by training and hardware aficionado"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-feed

markdown: kramdown
highlighter: rouge

kramdown:
  math_engine: null

atom_feed:
  hide: true

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/camattelaer"
    - label: "ORCID"
      icon: "fab fa-orcid"
      url: "https://orcid.org/0000-0002-8801-062X"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=C1_8_scAAAAJ"
    - label: "Sysadmin"
      icon: "fas fa-rss"
      url: "/feed.sysadmin.xml"
    - label: "CompChem"
      icon: "fas fa-rss"
      url: "/feed.computational-chemistry.xml"

collections:
  computational-chemistry:
    output: true
    permalink: /computational-chemistry/:path/
  sysadmin:
    output: true
    permalink: /sysadmin/:path/

show_excerpts: true

defaults:
  - scope:
      path: ""
    values:
      classes: single
      author_profile: false
  - scope:
      path: ""
      type: computational-chemistry
    values:
      layout: single
      classes: single
      author_profile: false
  - scope:
      path: ""
      type: sysadmin
    values:
      layout: single
      classes: single
      author_profile: false

paginate: 5
paginate_path: /page:num/

include:
 - _computational-chemistry
 - _sysadmin

feed:
  collections:
    computational-chemistry:
      path: "/feed.computational-chemistry.xml"
    sysadmin:
      path: "/feed.sysadmin.xml"

kramdown:
  toc_levels: "2..2"